// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsyiK02gSoHnnKfMqOspZYPPze_lSEBBo',
    appId: '1:490362617791:web:88792090728c5b0ae22b0a',
    messagingSenderId: '490362617791',
    projectId: 'drive-ease-1df0c',
    authDomain: 'drive-ease-1df0c.firebaseapp.com',
    databaseURL: 'https://drive-ease-1df0c-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ease-1df0c.firebasestorage.app',
    measurementId: 'G-958V2PMLZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpXk5_prstNklXYz83QWf05hQ5oL0mzKI',
    appId: '1:490362617791:android:767ad1e59ab3b9cae22b0a',
    messagingSenderId: '490362617791',
    projectId: 'drive-ease-1df0c',
    databaseURL: 'https://drive-ease-1df0c-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ease-1df0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh-AiY7RnPbOW2GOD2nbqvVcajNkoYqvk',
    appId: '1:490362617791:ios:d4b8f372c7477b91e22b0a',
    messagingSenderId: '490362617791',
    projectId: 'drive-ease-1df0c',
    databaseURL: 'https://drive-ease-1df0c-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ease-1df0c.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh-AiY7RnPbOW2GOD2nbqvVcajNkoYqvk',
    appId: '1:490362617791:ios:d4b8f372c7477b91e22b0a',
    messagingSenderId: '490362617791',
    projectId: 'drive-ease-1df0c',
    databaseURL: 'https://drive-ease-1df0c-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ease-1df0c.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsyiK02gSoHnnKfMqOspZYPPze_lSEBBo',
    appId: '1:490362617791:web:24ce5b8d007919eae22b0a',
    messagingSenderId: '490362617791',
    projectId: 'drive-ease-1df0c',
    authDomain: 'drive-ease-1df0c.firebaseapp.com',
    databaseURL: 'https://drive-ease-1df0c-default-rtdb.firebaseio.com',
    storageBucket: 'drive-ease-1df0c.firebasestorage.app',
    measurementId: 'G-G6BXSJ7VZH',
  );
}
